baseurl                 = "https://merlijn.sebrechts.be/"
DefaultContentLanguage  = "en"
title                   = "Merlijn Sebrechts"
theme                   = "hugo-future-imperfect-slim"
preserveTaxonomyNames   = true
paginate                = 10
disqusShortname         = "merlijn"
googleAnalytics         = "UA-172953075-1"
pluralizeListTitles     = false
disableLanguages        = [""]

[markup.goldmark.renderer]
unsafe= true

[outputs]
  home = ["html", "json", "rss"]

[params]
  mainSections = ["blog", "post"]
  # Loads CSS and JavaScript files. The variable is an array so that you can load
  # multiple/additional files if necessary. The standard theme files can be loaded
  # by adding the value, "default". Default includes the add-on.css and and-on.js.
  # Example: ["default", "/path/to/file"]
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  # Sets options for highlight.js
  highlightjs           = true
  highlightjsTheme      = "github"
  highlightjsLang       = ["html", "css", "js", "toml"]
  # Sets where "View More Posts" links to
  viewMorePostsLink     = "/blog/"
  # Activate Estimated Reading Times, which appear in the post headers
  readingTime           = false
  # Sets which Social Share links appear in posts.
  # Options are twitter, facebook, reddit, linkedin, stumbleupon, pinterest, email
  socialShare           = []

  [params.meta]
    # Sets the meta tag description
    description         = "Let's talk meta!"
    # Sets the meta tag author
    author              = "Merlijn Sebrechts"
    # If you would like to add more comprehensive favicon support passed root
    # directory favicon.ico, utlize this funtion. It is recommened to use
    # https://realfavicongenerator.net to generate your icons as that is the basis
    # for the theme's naming.
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff" # Copy from the https://realfavicongenerator.net
    iOSColor            = "#ffffff" # Copy from the https://realfavicongenerator.net

  [params.header]
    # Sets the navbarTitle that appears in the top left of the navigation bar
    navbarTitle         = "Merlijn Sebrechts"
    # Sets navbarTitle to match the section of the website
    dynamicTitles       = false
    searchMenu          = true
    shareMenu           = false
    languageMenu        = true

  # These are optional params related to the sidebar. They are recommended, but not
  # required for proper functionality. HTML is supported within the params.
  [params.intro]
    header                = "Merlijn Sebrechts"
    paragraph             = """Teaching and researching </br> computer science"""
    rssIntro              = true
    socialIntro           = true

    # This appears at the top of the sidebar above params.intro.header.
    # A width of less than 100px is recommended from a design perspective.
    [params.intro.pic]
      src                 = "/img/main/merlijn-sebrechts-square.jpg"
      # Masks image in a certain shape. Supported are circle, triangle, diamond, and hexagon.
      shape               = "circle"
      width               = ""
      alt                 = "Merlijn Sebrechts"

  [params.sidebar]
    about               = """Curious for more? <a href="/nl/">Check out the Dutch part of this blog.</a>"""
    # Sets the number of recent posts to show in the sidebar. The default value is 5.
    postAmount          = 5
    # set to show or to hide categories in the sidebar
    categories          = true
    # Sets Categories to sort by number of posts instead of alphabetical
    categoriesByCount   = true

  [params.footer]
    # Sets RSS icons to appear on the sidebar with the social media buttons
    rssFooter           = true
    # Sets Social Media icons to appear on the sidebar
    socialFooter        = true

[menu]
  # Sets the menu items in the navigation bar
  # Identifier prepends a Font Awesome icon to the menu item
  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    pre               = "<i class='fa fa-home'></i>"
    url               = "/"
    weight            = 1

  [[menu.main]]
    name              = "About"
    url               = "/about/"
    identifier        = "far fa-id-card"
    weight            = 2

  [[menu.main]]
    name              = "Blog"
    url               = "/blog/"
    identifier        = "far fa-newspaper"
    weight            = 3

  [[menu.main]]
    name              = "Tanzania (Dutch)"
    url               = "/nl/tanzania/"
    identifier        = "far fa-newspaper"
    weight            = 4

  [[menu.main]]
    name              = "Categories"
    url               = "/categories/"
    identifier        = "fas fa-sitemap"
    weight            = 5

[Languages]
  # Each language has its own menu.
  [Languages.en]
    languageCode        = "en"
    LanguageName        = "English"
    weight              = 1

  [Languages.nl]
    languageCode        = "nl"
    LanguageName        = "Nederlands"
    title               = "Merlijn Sebrechts"
    description         = "Meer context bij technologie"
    weight              = 2

  [Languages.nl.params]
    viewMorePostsLink     = "/tanzania/"


  [Languages.nl.params.intro]
    header                = "Merlijn Sebrechts"
    paragraph             = "Meer context bij technologie"
    rssIntro              = true
    socialIntro           = true


    # This appears at the top of the sidebar above params.intro.header.
    # A width of less than 100px is recommended from a design perspective.
    [Languages.nl.params.intro.pic]
      src                 = "/img/main/Merlijn Sebrechts100x100.jpg"
      # Masks image in a certain shape. Supported are circle, triangle, diamond, and hexagon.
      shape               = "circle"
      width               = ""
      alt                 = "Merlijn Sebrechts"

    [[Languages.nl.menu.main]]
      name              = "Tanzania"
      url               = "/tanzania"
      identifier        = "far fa-newspaper"
      weight            = 1

  #   [[Languages.nl.menu.main]]
  #     name              = "About"
  #     url               = "/about/"
  #     identifier        = "far fa-id-card"
  #     weight            = 2

    [[Languages.nl.menu.main]]
      name              = "Blog (Engels)"
      url               = "../blog/"
      identifier        = "far fa-newspaper"
      weight            = 3

    [[Languages.nl.menu.main]]
      name              = "Categorieën"
      url               = "/categories/"
      identifier        = "fas fa-sitemap"
      weight            = 5

# Sets Social Media icons to appear and link to your account. Value should be your
# username unless otherwise noted. These are the icons affected by socialAppearAtTop
# and socialAppearAtBottom.
[social]
  # Coding Communities
  github                = "merlijn-sebrechts"
  gitlab                = ""
  stackoverflow         = "" # User Number
  bitbucket             = ""
  jsfiddle              = ""
  codepen               = ""
  # Visual Art Communities
  deviantart            = ""
  flickr                = ""
  behance               = ""
  dribbble              = ""
  # Publishing Communities
  wordpress             = ""
  medium                = ""
  # Professional/Business Oriented Communities
  linkedin              = "merlijn-sebrechts"
  linkedin_company      = ""
  foursquare            = ""
  xing                  = ""
  slideshare            = ""
  # Social Networks
  facebook              = ""
  googleplus            = ""
  reddit                = ""
  quora                 = ""
  youtube               = ""
  vimeo                 = ""
  whatsapp              = "" # WhatsApp Number
    # WeChat and QQ need testing.
    wechat              = ""
    qq                  = "" # User ID Number
  instagram             = ""
  tumblr                = ""
  twitter               = "mesebrec"
  skype                 = ""
  snapchat              = ""
  pinterest             = ""
  telegram              = ""
  vine                  = ""
  googlescholar         = ""
  orcid                 = "0000-0002-4093-7338"
  researchgate          = ""
  # Email
  email                 = "merlijn.sebrechts@gmail.com"
